notifications:
  email: false
dist: xenial
os: linux
language: python
python: 3.8-dev
cache: pip
env:
  global:
  - GH_REPO=Drakkar-Software/simplifiedpytrends
  - DEPLOY_BRANCH=master
  - PACKAGE_FOLDER=simplifiedpytrends
install:
- python3 -m pip install -r requirements.txt -r dev_requirements.txt
jobs:
  include:
  - name: Linux - Python 3.8-dev - Python sources
    stage: test
    os: linux
    python: 3.8-dev
    language: python
    script:
    - python3 setup.py sdist bdist_wheel && python3 -m twine check dist/*
deploy:
  - provider: pypi
    user: __token__
    password:
      secure: fSkyL3XwJj8f/4oN/A3gmePvPfFqB4kRuaGDQBUMjcwL9+LUl4Y5BpSDU+zmx2uKjbdMiyHXMzuHuZOud5DyXN/cHlGeyu0GC2Gn1ot5V/M0N8SXjEKfPyOeHcFHk1Lv2QPMBT+XV6S7DXlF1IV4/Q6E8el3If5b9FRaFGAsHQgsR5PbrYSBhLJnHVEQRT2nGR+S/XL6eYkfI/x8CogQaXPlXEoOaRAQoS2tYDHqyeeiGOqBcazmx6/GIeSrK82ktR9ZuZtKCPhp1wKHSt/9MxY0ZjWWU8Smp7oDdD1dNfybXTUd9TSqzxdoWwk6/OoS5icZ+rLSZ8KJeEvRXV7g72zRmEuzcXHXzMq3QHhGZuUNmJekKoKvzaXgpbzQOwyMnUN2CxcKlj+6T3cm2gWU0p2c4uTrRh2MaI/2DPlc0nUmCNrtkwg5e/TX5zp+t/qgJegNgHOU+nwZ9yW2aR35hX5gI6V9Ry3Yh3wU9jnCBbECymIbJBf3aGh7hKfZCbBFsIXJZfao054Edu/0eyRd6HJXn6PvrqsxtL4MFP9Z8Zeekp1IhZHDA9mpxuPqVBAnIUwSCnC30NdIpjqhy0vEpJbb+Sbelp80H57CNS/K9ax8h/V/eqPONa/y3dEub3HBDzbv6+2SQAtzsge6YaV48jlzwf2ssR672scy8YC4vI8=
    skip_existing: true
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      repo: Drakkar-Software/simplifiedpytrends
      branch: master
      tags: true
      condition: "$TRAVIS_OS_NAME = 'linux'"